### ISSUE TITLE
Update Checkin Rating with Ecommerce Items

### ISSUE THREAD

**Issue by pchainho** [reTHINK-project/dev-java-hyperty#18]
As specified [here](https://github.com/reTHINK-project/specs/tree/master/datamodel/data-objects/ecommerce)

- [x] create Mongo collection and add entries
- [x] update [CheckinRatingHyperty ](https://github.com/reTHINK-project/dev-java-hyperty/blob/develop/src/main/java/tokenRating/CheckInRatingHyperty.java#L62)
- [x] CheckInRatingHypertyTest: [retrieve bonus items](https://github.com/reTHINK-project/dev-java-hyperty/blob/develop/src/test/java/hyperty/CheckInTest.java#L210)
- [x] update [StartJavaHyperties ](https://github.com/reTHINK-project/dev-java-hyperty/blob/develop/src/main/java/runHyperties/StartJavaHyperties.java#L139)

**Comment by Felgueiras** [comment]
what's the name for the new Mongo collection?
