### ISSUE TITLE
Checkin Rating: update to control eCommerce items spent in the Spots 

### ISSUE THREAD

**Issue by pchainho** [reTHINK-project/dev-java-hyperty#23]
[E-commerce Data Object](https://rethink-project.github.io/specs/datamodel/data-objects/ecommerce/readme/?scroll=2940)
- [x] wallet `bonus-credit` field: amount of tokens available to spend on bonus (que é descontado por cada bónus levantado e no qual tb são creditados os pontos ganhos)
- [x] Check if changes in the object contains the itemId and in that case it is an attempt to consume an eCommerce Item
- [x] Validate user has at least `item.cost` points
- [x] Validate item consume is valid taking into account the time (`item.start` and `item.expires`)
- [x] Validate `item.constraints`
- [x] create new Wallet transaction similar with checkin but having as amount the negative value of `item.cost`

- [x] `transaction.data`

- [x] transaction `bonus` field: true if transaction is related to a bonus item false otherwise

**Transaction outcomes:**

- [x] valid

- [x] invalid-insufficient-credits

- [x]  invalid-not-available

- [x]  invalid-failed-constraints

**Comment by Felgueiras** [comment]
@pchainho  example of `item.constraints`?

**Comment by pchainho** [comment]
X times in y period of time eg once a day

**Comment by Felgueiras** [comment]
how does `bonus-credit` work? When wallet created what's its initial value? How is it updated?

**Comment by pchainho** [comment]
Like the normal wallet balance. All transactions amount that are not bonus collect, are added both to wallet balance and bonus credit.

**Comment by Felgueiras** [comment]
I'm not seeing the difference from the wallet.balance, they will be the same value if initialized with the same amount

**Comment by Felgueiras** [comment]
Besides the wallet balance, should the amount of bonus credits be available on the UI as well?

**Comment by pchainho** [comment]
Humm perhaps in the bonus screen. But most of all it is to be used to control if there is enough credit to collect bonus.

Enviado do meu telefone Huawei.

-------- Mensagem original --------
Assunto: Re: [reTHINK-project/dev-java-hyperty] Checkin Rating: update to control eCommerce items spent in the Spots (#23)
De: Rafael Salgueiro Felgueiras Pinto
Para: reTHINK-project/dev-java-hyperty
CC: Paulo Chainho ,Mention


Besides the wallet balance, should the amount of bonus credits be available on the UI as well?
