### ISSUE TITLE
Wallet Manager: Wallet not found

### ISSUE THREAD

**Issue by pchainho** [reTHINK-project/dev-java-hyperty#24]
Sometimes when receiving new transactions from rating hyperties, individual wallets are not found and transactions are not processes.

**Comment by pchainho** [comment]
I suspect the issues is completely fixed:
![image](https://user-images.githubusercontent.com/3893553/43015084-61fed396-8c46-11e8-8541-9ddd4375c735.png)

**Comment by Felgueiras** [comment]
remove this [line ](https://github.com/reTHINK-project/dev-java-hyperty/blob/develop/src/main/java/walletManager/WalletManagerHyperty.java#L453)
