### ISSUE TITLE
Regular Bonus offer (eg every 3 monts) for Cause leader supporters

### ISSUE THREAD

**Issue by Felgueiras** [reTHINK-project/dev-java-hyperty#38]
These offer bonus will be identical to regular ones, with the following additional fields:
- "cause": cause id
- "cost": 0

There should be a script which will, at the end of every month, check which cause has more points and update the DB:

- `start`: current date
- `expires`: `start` + 1 week
- `cause`: ID of cause with more points

**Config:**

- bonusID
- causes: IDs

**Comment by pchainho** [comment]
instead of "cause" it should be related with who can consume this bonus eg `target: { cause: <id> }

**Comment by pchainho** [comment]
there will be a single Cause Leader bonus that will be updated by the script when required.
