### ISSUE TITLE
Check-in Rating Hyperty implementation

### ISSUE THREAD

**Issue by pchainho** [reTHINK-project/dev-java-hyperty#4]
See [spec](https://github.com/reTHINK-project/dev-java-hyperty/blob/master/docs/token-rating/checkin-rating.md)

**Comment by Felgueiras** [comment]
values to be defined:
- ammount of tokens per checkin
- max difference between user and shop coordinates (for a valid checkin)
- min temporal difference between current and last checkin

**Comment by pchainho** [comment]
Added as config data
