### ISSUE TITLE
CountDownLatches associated with Mongo are blocking Verticle instances

### ISSUE THREAD

**Issue by pchainho** [reTHINK-project/dev-java-hyperty#45]
Options:

1-  [Java Future](https://www.baeldung.com/java-future)

2-  [Verticle Sync](https://vertx.io/docs/vertx-sync/java/)

3- [Worker Verticle](https://vertx.io/docs/vertx-core/groovy/#worker_verticles)

**Comment by Felgueiras** [comment]
Currently using [Vert.x Future](https://vertx.io/docs/guide-for-java-devs/#_a_word_on_vert_x_future_objects_and_callbacks)
