### ISSUE TITLE
Wallet Manager Hyperty implementation

### ISSUE THREAD

**Issue by pchainho** [reTHINK-project/dev-java-hyperty#5]
see [spec](https://github.com/reTHINK-project/dev-java-hyperty/tree/master/docs/wallet-manager)

- [x] support profile

- [x] support ranking - ranking of all users are schedulled to be updated every x time eg 3600 sec 

- [x] `config.rankingTimer`: num of milliseconds before calling `generateRankings()` and update wallet rankings

- [x] publish changes only when `ranking` changes

**Comment by Felgueiras** [comment]
wallet address still needs to be generated by crypto function, after that tests need to be updated to stop using harcoreded address

**Comment by Felgueiras** [comment]
wallet addresses generated by SHA-256 digest function, tests now use generated wallet addresses
