### ISSUE TITLE
Energy Saving Rating

### ISSUE THREAD

**Issue by pchainho** [reTHINK-project/dev-java-hyperty#9]
See [spec](https://github.com/reTHINK-project/dev-java-hyperty/blob/master/docs/token-rating/energy-saving-rating.md#rating-invitation)

- [x] private rating algorithm
- [x] public rating algorithm

- [x] reset cause wallet counters after processing energy saving for the month

**Comment by Felgueiras** [comment]
- [ ] how will the Java hyperty know which participants support which cause?

**Comment by Felgueiras** [comment]
how will participants's cause be known (app -> backend)?

**Comment by Felgueiras** [comment]
@Felgueiras  that info is sent when wallet is created

**Comment by Felgueiras** [comment]
@pchainho:
- how will the Hyperty distinguish between public and private data?
- what's the rating algorithm?

**Comment by pchainho** [comment]
The Smart IoT protostub should be able to distinguish public and private devices / buildings from the identity data received when requested to setup a new device.

Algorithms are defined in the PPT sent sometime ago
